# Generated by Django 4.0.7 on 2022-09-06 16:13

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
                name='WoeidModel',
                fields=[
                    ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                    verbose_name='created')),
                    ('modified',
                     model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                              verbose_name='modified')),
                    ('id', models.CharField(max_length=90, primary_key=True, serialize=False, verbose_name='id')),
                    ('country', models.CharField(max_length=256, verbose_name='country')),
                    ('cc', models.CharField(max_length=5, verbose_name='country code')),
                    ('active', models.BooleanField(default=True, verbose_name='active')),
                ],
                options={
                    'abstract': False,
                },
        ),
    ]
